### ISSUE TITLE
Error when using MultiLogger in a Rails app

### ISSUE THREAD

**Issue by jgmartin** [dwbutler/logstash-logger#60]
I'm attempting to use a MultiLogger within a Rails app to retain file system logging while also pushing logs to Logstash.  I'm seeing the following error:

    undefined method `[]=' for #<Logger:0x007fb180089178>

when using the following configuration:

    # Required
    config.logstash.type = :multi_logger

     # Required. Each logger may have its own formatter.
     config.logstash.outputs = [
       {
         type: :file,
         path: "log/#{Rails.env}.log",
         formatter: Logger::Formatter
       },
       {
         type: :udp,
         port: port,
         host: host,
         formatter: :json
       }
     ]

Any other logger type works fine (including a MultiDelegator, though in that case i can't specify different formatters, which is a requirement).   The full stack trace is linked below:

https://gist.github.com/jgmartin/96a9219367e6faabcd05

Any help is much appreciated.  Thanks.

**Comment by jgmartin** [comment]
Just tested this is a brand new test rails app (rails 4.2.4) and the failure is the same as in our application.  It appears to be an issue with rack middleware seeing the logger where it expects a request object.

**Comment by dwbutler** [comment]
Here is the offending line of code from the [RequestId middleware](https://github.com/rails/rails/blob/dac822ef58ae05f0e805222fa8744116080165ac/actionpack/lib/action_dispatch/middleware/request_id.rb#L21)

I suspect that there is a Rack middleware that is returning the Rails logger object instead of doing `@app.call`. I'll generate a new Rails app and try it out.

**Comment by dwbutler** [comment]
I created a new Rails app and reproduced the problem. I ran `bin/rake middleware` and noticed the following:

```
use ActionDispatch::RequestId
use Rails::Rack::Logger
```

So the `Rails::Rack::Logger` middleware comes right before the `RequestId` middleware. I believe the offending line of code is [here](https://github.com/rails/rails/blob/dac822ef58ae05f0e805222fa8744116080165ac/railties/lib/rails/rack/logger.rb#L20). Notice how it's using tagged logging.

LogStashLogger implements a version of tagged logging based on ActiveSupport's tagged logging. It seems there must be a difference that is causing the middleware to return the logger instead of the contents of the block passed to the logger. I will continue to investigate.

**Comment by dwbutler** [comment]
Fix released in 0.14.1. `MultiLogger` had a custom tagged logging implementation which wasn't necessary and broke under Rails. All loggers will share the same tags without forwarding the call to each logger, because the tags are stored in a thread local variable.
