### ISSUE TITLE
Multi_logger doesn't respect specified logging formatter

### ISSUE THREAD

**Issue by KnownSubset** [dwbutler/logstash-logger#61]
When configuring a **multi_logger** LogStashLogger, the provided formatter is ignored and the default formatter is used.  The specified formatter should the one that is used to write out to the output.

Example configuration
```
config.logger = LogStashLogger.new(
  type: :multi_logger,
  outputs: [
    { type: :file, path: "log/development.log", formatter: ::Logger::Formatter, sync: true }
  ]
)
```
Log file output:
```
{"message":"","@timestamp":"2015-10-05...","@version":"1"...}
{"message":"","@timestamp":"2015-10-05...","@version":"1"...}
{"message":"Started GET \"/\" for 192.168.59.3 at 2015-10-05 21:32:33 +0000","@timestamp":"2015-10-05...","@version":"1"...}
```

**Comment by dwbutler** [comment]
The problem is in the implementation of [MultiLogger#formatter=](https://github.com/dwbutler/logstash-logger/blob/master/lib/logstash-logger/multi_logger.rb#L25-L29), which overrides the formatter on each logger. LogStashLogger sets the formatter to the default `JsonLines` if no formatter is specified.

I think it would be reasonable to change the implementation of MultiLogger so it only sets the formatter of each logger if a formatter isn't already specified.

**Comment by dwbutler** [comment]
Fix released in 0.15.1.

**Comment by KnownSubset** [comment]
:+1: 
Thanks for the quick fix!

**Comment by dwbutler** [comment]
No problem! Thanks for the bug report!
