### ISSUE TITLE
Options for Mitigating Input Downtime

### ISSUE THREAD

**Issue by todd** [dwbutler/logstash-logger#68]
We recently experienced an issue where our Redis input for Logstash went down and our app became unresponsive, a scenario outlined in the [README](https://github.com/dwbutler/logstash-logger#buffering--automatic-retries). As noted in the README, we can bump up the values for the buffer configuration, but it doesn't seem that that will prevent this issue from recurring in the event of another significant logging infrastructure downtime event.

There's the `sync` option, but, based on the documentation, I'm unclear on whether this would have prevented this issue from occurring.

It would be great if there was a way for the logger to flush the buffer if it receives a connection error. We'd much rather lose logs than take downtime. Is this something that would be possible? I'd be more than willing to work on a patch and submit a PR if you thought it was possible and worthwhile and could give a little direction.

**Comment by johnnonolan** [comment]
:+1:

**Comment by dwbutler** [comment]
I think it's a great idea to make this behavior configurable. I think most people would rather drop some logs rather than experience downtime! :)

In order for this to work really well, LogStashLogger would need to never block and never raise an exception. This would require a thorough review of the code to make sure this works consistently everywhere.

I can see there being different options for this. Don't buffer messages, and drop messages on connection failure. Buffer messages, but drop them if the buffer gets full. Buffer messages, but don't drop them. (e.g. block until the connection is re-established.)

**Comment by blysik** [comment]
I think we experienced the same thing recently: our redis system was down, and this seemed to cause long pauses because of timeouts sending logs to it in our Rails application.

Is there a way to make a very short timeout for logging?

**Comment by dwbutler** [comment]
The Ruby [Redis client](http://www.rubydoc.info/github/redis/redis-rb/Redis/Client) defaults to a 5 second timeout. You can override it by passing a different value for `timeout` and/or `connect_timeout` in your Redis configuration. Let me know if that helps with the issue.

**Comment by todd** [comment]
So we're not going to work on this due to time and resource constraints, but I did want to report back with the solution we went with.

We ended up removing this gem entirely. Instead, we're logging to files that are being tailed with [Filebeat][1] and shipping events directly to our collectors.

I regret that I won't be able to work on this. I'm going to leave this issue open for now as it's still an issue  that I believe should be solved at some point.

[1]: https://www.elastic.co/products/beats/filebeat

**Comment by dwbutler** [comment]
I agree that it should be solved. LogStashLogger is essentially an in-process log shipper, and should act in a well-defined, reliable way that does not interfere with normal operation of the application.

**Comment by DaveCollinsJr** [comment]
We were bitten by this in production today also.  Our ELK stack went down over the weekend and eventually, I believe, the inability to log caused our sidekiq workers to get hung.  Would +1 the option to simply lose the data when the buffer is full rather than having the application become unresponsive.

**Comment by DaveCollinsJr** [comment]
Thanks much @sauliusgrigaitis for that fix!

**Comment by lucke84** [comment]
Hello there, we've experienced yesterday the same issue (our Redis endpoint went down and the application quickly became unresponsive). @dwbutler What needs to be done to introduce the ability to drop the data if the connection times out? I'd be happy to help if you give me a few pointers on what code to review (as you were suggesting in this very issue).

**Comment by dwbutler** [comment]
I finally found some time to work on this. Please try the patch in #81. By default, the logger will no longer block when there is a connection error. If you want to drop messages when the buffer is full, add this new configuration option to your logger:

```ruby
logger = LogStashLogger.new(type: :redis, drop_messages_on_full_buffer: true)
```

**Comment by lucke84** [comment]
Thanks @dwbutler for getting this done! Any chance you'll release a new version of the gem anytime soon?

**Comment by dwbutler** [comment]
Yes, my goal is to release sometime this week.
